name: Staging CD

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: HRD-ENV

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          debug: true
          script: |
            cd staging/LPK-LKP-DM-BE
            git pull origin development
            npm run prisma:migrate
            npm run prisma:seed:dev
            npm i
            pm2 restart 13
        