name: Deploy Backend via SSH

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: SECRET  # Use the environment 'SECRET' for secrets

    steps:
    - name: Install SSH Client
      run: sudo apt-get install -y sshpass

    - name: Deploy to SSH server
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e
          mkdir -p ${{ secrets.APP_DIR }}
          cd ${{ secrets.APP_DIR }}

          if [ ! -d ".git" ]; then
            git clone ${{ secrets.REPO_URL }} . 
          else
            git pull origin main
          fi

          # Source NVM to use npm and node
          source /root/.nvm/nvm.sh

          # Now you can run npm and node
          /root/.nvm/versions/node/v23.3.0/bin/npm install
          /root/.nvm/versions/node/v23.3.0/bin/pm2 restart 13
        EOF
