name: Deploy App with Prisma to VPS

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup SSH key for GitHub Actions
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Sync Files to VPS (exclude .env and uploads folder)
      run: |
        rsync -avz --delete --exclude '.env' --exclude 'uploads/' -e "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/staging/LPK-LKP-DM-BE

    - name: Install Dependencies and Run Prisma Migrations
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.VPS_HOST_PROD }} << 'EOF'
          # Set the Node.js version to 20.x if it's not already set
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # Load NVM
          nvm install 20
          nvm use 20

          # Verify Node.js version
          node -v

          # Install PM2 if not already installed
          npm install -g pm2

          # Go to the app directory
          cd /root/staging/LPK-LKP-DM-BE

          # Install dependencies
          npm install

          # Run Prisma Migrations
          npx prisma migrate deploy

        EOF
