name: Staging CD

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: SECRET

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          debug: true
          script: |
            cd staging/LPK-LKP-DM-BE
            git reset --hard
            git pull origin development

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            npm install
            npm run prisma:migrate
            npm run prisma:seed:dev
            pm2 restart 13 || pm2 start npm --name backend -- run start
