name: Deploy with Prisma to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install SSH and SSHPass
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass openssh-client rsync

    - name: Sync Files to VPS (exclude .env and necessary folder)
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" rsync -avz --delete \
          --exclude='.env' \
          --exclude='logs/' \
          --exclude='public/' \
          --exclude='uploads/' \
          -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" \
          ./ ${{ secrets.SSH_USER_PROD }}@${{ secrets.SSH_HOST_PROD }}:/root/staging/LPK-LKP-DM-BE

    - name: Install Dependencies and Run Prisma Migrations
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          # Set the Node.js version to 20.x if it's not already set
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # Load NVM
          nvm install 20
          nvm use 20

          # Verify Node.js version
          node -v

          # Install PM2 if not already installed
          npm install -g pm2

          # Go to the app directory
          cd /root/staging/LPK-LKP-DM-BE

          # Install dependencies
          npm install

          # Run Prisma Migrations
          npx prisma migrate deploy

        EOF
