name: Deploy Backend via SSH (STAGING)

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: SECRET

    steps:
    - name: Install SSH Client
      run: sudo apt-get install -y sshpass

    - name: Deploy to SSH server
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
          set -e
          mkdir -p ${{ secrets.STG_APP_DIR }}
          cd ${{ secrets.STG_APP_DIR }}

          if [ ! -d ".git" ]; then
            git clone ${{ secrets.REPO_URL }} . 
          else
            git pull origin development
          fi

          npm install
          npm run dev
          # pm2 restart
        EOF
